// FLOW Mock Data — Realistic seed data for demonstration
import type { Task, Project, Area, Note, Habit, CalendarEvent, InboxItem, Analytics, User, FocusSession } from './types';

export const mockUser: User = {
  id: 'user-1',
  email: 'brent@flow.app',
  name: 'Brent',
  timezone: 'America/New_York',
  workStartHour: 9,
  workEndHour: 18,
  productivityScore: 78,
  totalFocusMinutes: 2340,
  currentStreak: 7,
  longestStreak: 21,
  karmaPoints: 1240,
};

export const mockProjects: Project[] = [
  { id: 'proj-1', name: 'Work', color: '#D97706', icon: 'Briefcase', status: 'ACTIVE', taskCount: 12, completedCount: 8 },
  { id: 'proj-2', name: 'Personal', color: '#0891B2', icon: 'House', status: 'ACTIVE', taskCount: 7, completedCount: 3 },
  { id: 'proj-3', name: 'Side Project', color: '#16A34A', icon: 'Rocket', status: 'ACTIVE', taskCount: 5, completedCount: 1 },
  { id: 'proj-4', name: 'Learning', color: '#7C3AED', icon: 'BookOpen', status: 'ACTIVE', taskCount: 4, completedCount: 2 },
];

export const mockAreas: Area[] = [
  { id: 'area-1', name: 'Health', icon: 'Heart', color: '#DC2626' },
  { id: 'area-2', name: 'Finance', icon: 'CurrencyDollar', color: '#16A34A' },
  { id: 'area-3', name: 'Relationships', icon: 'Users', color: '#7C3AED' },
];

const today = new Date().toISOString().split('T')[0];
const tomorrow = new Date(Date.now() + 86400000).toISOString().split('T')[0];
const yesterday = new Date(Date.now() - 86400000).toISOString().split('T')[0];
const nextWeek = new Date(Date.now() + 7 * 86400000).toISOString().split('T')[0];

export const mockTasks: Task[] = [
  {
    id: 'task-1',
    title: 'Review Q1 product roadmap with team',
    status: 'TODO',
    priority: 'HIGH',
    dueDate: today,
    estimatedMinutes: 60,
    projectId: 'proj-1',
    project: mockProjects[0],
    order: 0,
    createdAt: yesterday,
    updatedAt: yesterday,
  },
  {
    id: 'task-2',
    title: 'Write weekly engineering update',
    status: 'IN_PROGRESS',
    priority: 'MEDIUM',
    dueDate: today,
    estimatedMinutes: 30,
    projectId: 'proj-1',
    project: mockProjects[0],
    order: 1,
    createdAt: yesterday,
    updatedAt: today,
  },
  {
    id: 'task-3',
    title: 'Schedule dentist appointment',
    status: 'TODO',
    priority: 'LOW',
    dueDate: tomorrow,
    estimatedMinutes: 15,
    projectId: 'proj-2',
    project: mockProjects[1],
    order: 2,
    createdAt: yesterday,
    updatedAt: yesterday,
  },
  {
    id: 'task-4',
    title: 'Deploy v2.1 to production',
    status: 'TODO',
    priority: 'URGENT',
    dueDate: today,
    estimatedMinutes: 45,
    projectId: 'proj-3',
    project: mockProjects[2],
    order: 3,
    createdAt: yesterday,
    updatedAt: yesterday,
  },
  {
    id: 'task-5',
    title: 'Read "Deep Work" chapter 3',
    status: 'TODO',
    priority: 'LOW',
    dueDate: nextWeek,
    estimatedMinutes: 40,
    projectId: 'proj-4',
    project: mockProjects[3],
    order: 4,
    createdAt: yesterday,
    updatedAt: yesterday,
  },
  {
    id: 'task-6',
    title: 'Prepare investor deck slides',
    status: 'TODO',
    priority: 'HIGH',
    dueDate: tomorrow,
    estimatedMinutes: 120,
    projectId: 'proj-1',
    project: mockProjects[0],
    order: 5,
    createdAt: yesterday,
    updatedAt: yesterday,
  },
  {
    id: 'task-7',
    title: 'Fix authentication bug in mobile app',
    status: 'IN_PROGRESS',
    priority: 'URGENT',
    dueDate: today,
    estimatedMinutes: 90,
    projectId: 'proj-3',
    project: mockProjects[2],
    order: 6,
    createdAt: yesterday,
    updatedAt: today,
  },
  {
    id: 'task-8',
    title: 'Update portfolio website',
    status: 'TODO',
    priority: 'MEDIUM',
    dueDate: nextWeek,
    estimatedMinutes: 180,
    projectId: 'proj-2',
    project: mockProjects[1],
    order: 7,
    createdAt: yesterday,
    updatedAt: yesterday,
  },
  {
    id: 'task-9',
    title: 'Research competitors for market analysis',
    status: 'DONE',
    priority: 'MEDIUM',
    dueDate: yesterday,
    completedAt: yesterday,
    estimatedMinutes: 60,
    projectId: 'proj-1',
    project: mockProjects[0],
    order: 8,
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    updatedAt: yesterday,
  },
  {
    id: 'task-10',
    title: 'Set up automated testing pipeline',
    status: 'DONE',
    priority: 'HIGH',
    dueDate: yesterday,
    completedAt: yesterday,
    estimatedMinutes: 120,
    projectId: 'proj-3',
    project: mockProjects[2],
    order: 9,
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    updatedAt: yesterday,
  },
  {
    id: 'task-11',
    title: 'Call mom for birthday',
    status: 'TODO',
    priority: 'HIGH',
    dueDate: today,
    estimatedMinutes: 30,
    projectId: 'proj-2',
    project: mockProjects[1],
    order: 10,
    createdAt: today,
    updatedAt: today,
  },
  {
    id: 'task-12',
    title: 'Review pull requests from team',
    status: 'TODO',
    priority: 'MEDIUM',
    dueDate: today,
    estimatedMinutes: 45,
    projectId: 'proj-1',
    project: mockProjects[0],
    order: 11,
    createdAt: today,
    updatedAt: today,
  },
];

export const mockNotes: Note[] = [
  {
    id: 'note-1',
    title: 'Product Strategy 2025',
    content: { type: 'doc', content: [] },
    contentText: 'Key strategic initiatives for the year ahead. Focus on user retention and expansion into enterprise...',
    projectId: 'proj-1',
    project: mockProjects[0],
    isPinned: true,
    wordCount: 847,
    createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    updatedAt: yesterday,
  },
  {
    id: 'note-2',
    title: 'Meeting Notes — Engineering Sync',
    content: { type: 'doc', content: [] },
    contentText: 'Discussed deployment pipeline improvements. Action items: 1) Set up staging environment...',
    projectId: 'proj-1',
    project: mockProjects[0],
    wordCount: 312,
    createdAt: yesterday,
    updatedAt: yesterday,
  },
  {
    id: 'note-3',
    title: 'Book Notes: Deep Work',
    content: { type: 'doc', content: [] },
    contentText: 'Cal Newport argues that the ability to focus without distraction is becoming increasingly rare...',
    projectId: 'proj-4',
    project: mockProjects[3],
    isFavorite: true,
    wordCount: 523,
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'note-4',
    title: 'Side Project Ideas',
    content: { type: 'doc', content: [] },
    contentText: 'AI-powered journaling app, productivity tracker with ML insights, developer tools...',
    projectId: 'proj-3',
    project: mockProjects[2],
    wordCount: 198,
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    id: 'note-5',
    title: 'Weekly Review Template',
    content: { type: 'doc', content: [] },
    contentText: 'What went well this week? What could be improved? Key learnings...',
    isPinned: false,
    wordCount: 156,
    createdAt: new Date(Date.now() - 14 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
];

export const mockHabits: Habit[] = [
  {
    id: 'habit-1',
    name: 'Morning Workout',
    description: '30 minutes of exercise',
    icon: 'Lightning',
    color: '#D97706',
    frequency: 'DAILY',
    targetCount: 1,
    currentStreak: 7,
    longestStreak: 21,
    completedToday: true,
    completedDates: generateCompletedDates(7),
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'habit-2',
    name: 'Read 20 Pages',
    description: 'Read a non-fiction book',
    icon: 'BookOpen',
    color: '#7C3AED',
    frequency: 'DAILY',
    targetCount: 1,
    currentStreak: 4,
    longestStreak: 12,
    completedToday: false,
    completedDates: generateCompletedDates(4),
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
  {
    id: 'habit-3',
    name: 'Meditate',
    description: '10 minutes of mindfulness',
    icon: 'Brain',
    color: '#0891B2',
    frequency: 'DAILY',
    targetCount: 1,
    currentStreak: 12,
    longestStreak: 30,
    completedToday: true,
    completedDates: generateCompletedDates(12),
    createdAt: new Date(Date.now() - 45 * 86400000).toISOString(),
  },
  {
    id: 'habit-4',
    name: 'No Social Media',
    description: 'Avoid social media before noon',
    icon: 'PhoneSlash',
    color: '#16A34A',
    frequency: 'DAILY',
    targetCount: 1,
    currentStreak: 3,
    longestStreak: 8,
    completedToday: false,
    completedDates: generateCompletedDates(3),
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: 'habit-5',
    name: 'Journal',
    description: 'Write morning pages',
    icon: 'PencilLine',
    color: '#DC2626',
    frequency: 'DAILY',
    targetCount: 1,
    currentStreak: 2,
    longestStreak: 15,
    completedToday: true,
    completedDates: generateCompletedDates(2),
    createdAt: new Date(Date.now() - 60 * 86400000).toISOString(),
  },
  {
    id: 'habit-6',
    name: 'Drink 8 Glasses Water',
    description: 'Stay hydrated',
    icon: 'Drop',
    color: '#2563EB',
    frequency: 'DAILY',
    targetCount: 8,
    currentStreak: 5,
    longestStreak: 14,
    completedToday: false,
    completedDates: generateCompletedDates(5),
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
];

function generateCompletedDates(streak: number): string[] {
  const dates: string[] = [];
  for (let i = 0; i < streak; i++) {
    dates.push(new Date(Date.now() - i * 86400000).toISOString().split('T')[0]);
  }
  // Add some random past dates for the heatmap
  for (let i = streak + 1; i < 90; i++) {
    if (Math.random() > 0.3) {
      dates.push(new Date(Date.now() - i * 86400000).toISOString().split('T')[0]);
    }
  }
  return dates;
}

export const mockCalendarEvents: CalendarEvent[] = [
  {
    id: 'event-1',
    title: 'Team Standup',
    startTime: `${today}T09:00:00`,
    endTime: `${today}T09:30:00`,
    isAllDay: false,
    color: '#D97706',
    source: 'flow',
  },
  {
    id: 'event-2',
    title: 'Product Review',
    description: 'Q1 roadmap review with stakeholders',
    startTime: `${today}T14:00:00`,
    endTime: `${today}T15:30:00`,
    isAllDay: false,
    color: '#0891B2',
    source: 'google',
  },
  {
    id: 'event-3',
    title: '1:1 with Manager',
    startTime: `${tomorrow}T10:00:00`,
    endTime: `${tomorrow}T10:30:00`,
    isAllDay: false,
    color: '#16A34A',
    source: 'flow',
  },
  {
    id: 'event-4',
    title: 'Deep Work Block',
    startTime: `${today}T09:30:00`,
    endTime: `${today}T12:00:00`,
    isAllDay: false,
    color: '#7C3AED',
    source: 'flow',
    taskId: 'task-4',
  },
];

export const mockInboxItems: InboxItem[] = [
  {
    id: 'inbox-1',
    content: 'Call dentist tomorrow at 3pm',
    type: 'TASK',
    processed: false,
    createdAt: new Date(Date.now() - 2 * 3600000).toISOString(),
  },
  {
    id: 'inbox-2',
    content: 'Great article about distributed systems: https://example.com/article',
    type: 'NOTE',
    processed: false,
    createdAt: new Date(Date.now() - 5 * 3600000).toISOString(),
  },
  {
    id: 'inbox-3',
    content: 'Team lunch next Friday at noon',
    type: 'EVENT',
    processed: false,
    createdAt: new Date(Date.now() - 1 * 3600000).toISOString(),
  },
  {
    id: 'inbox-4',
    content: 'Build a habit tracker app with streak visualization',
    type: 'IDEA',
    processed: false,
    createdAt: new Date(Date.now() - 8 * 3600000).toISOString(),
  },
];

export const mockAnalytics: Analytics[] = Array.from({ length: 30 }, (_, i) => ({
  date: new Date(Date.now() - i * 86400000).toISOString().split('T')[0],
  tasksCompleted: Math.floor(Math.random() * 8) + 2,
  tasksCreated: Math.floor(Math.random() * 5) + 3,
  focusMinutes: Math.floor(Math.random() * 120) + 30,
  pomodorosCompleted: Math.floor(Math.random() * 6) + 1,
  habitsCompleted: Math.floor(Math.random() * 5) + 1,
  habitsTotal: 6,
  productivityScore: Math.floor(Math.random() * 30) + 60,
}));

export const mockFocusSessions: FocusSession[] = [
  {
    id: 'focus-1',
    taskId: 'task-2',
    task: mockTasks[1],
    type: 'POMODORO',
    startedAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    endedAt: new Date(Date.now() - 1.5 * 3600000).toISOString(),
    durationMin: 25,
    completed: true,
    ambientSound: 'lofi',
  },
  {
    id: 'focus-2',
    taskId: 'task-7',
    task: mockTasks[6],
    type: 'DEEP_WORK',
    startedAt: new Date(Date.now() - 4 * 3600000).toISOString(),
    endedAt: new Date(Date.now() - 3 * 3600000).toISOString(),
    durationMin: 60,
    completed: true,
    ambientSound: 'rain',
  },
];
